[2022-08-30 15:57:18.886+0300] [ERROR   ] -  query ("") failed with error: Driver not loaded Driver not loaded (sqlwrapper.py:7)
[2022-08-30 16:01:14.393+0300] [ERROR   ] -  query ("") failed with error: Driver not loaded Driver not loaded (sqlwrapper.py:7)
[2022-08-30 17:08:02.552+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET ddm_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:08:02.554+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET xra_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:08:03.947+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET trp_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:09:05.479+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET dia_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:09:05.480+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET usd_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:09:09.104+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET oak_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:09:09.105+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET glu_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:09:09.105+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET dia_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:09:09.106+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET xra_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:09:09.106+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET cts_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 17:09:09.107+0300] [ERROR   ] - UPDATE query ("UPDATE patient_info SET usd_follow = ? WHERE patient_id = ?") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-08-30 20:37:19.401+0300] [CRITICAL] - Uncaught Exception:
Traceback (most recent call last):
  File "C:/Users/Aleee/!AlertApp/main.py", line 218, in <module>
    w = MainWindow()
  File "C:/Users/Aleee/!AlertApp/main.py", line 27, in __init__
    self.set_connections()
  File "C:/Users/Aleee/!AlertApp/main.py", line 67, in set_connections
    chb.stateChanged.connnect(lambda: self.set_filter)
AttributeError: 'PyQt5.QtCore.pyqtBoundSignal' object has no attribute 'connnect' (__init__.py:95)
[2022-08-31 11:39:54.269+0300] [ERROR   ] - UPDATE query ("UPDATE instrtest SET status = 5, datetime = ? WHERE test_type = ? AND status IN (1, 3)") failed with error: Parameter count mismatch (sqlwrapper.py:7)
[2022-09-02 15:50:08.156+0300] [CRITICAL] - Uncaught Exception:
Traceback (most recent call last):
  File "C:/Users/Aleee/!AlertApp/main.py", line 95, in <module>
    w = MainWindow()
  File "C:/Users/Aleee/!AlertApp/main.py", line 52, in __init__
    self.thread_1.started.connect(self.emulator.update)
AttributeError: 'Emulator' object has no attribute 'update' (__init__.py:95)
[2022-09-29 19:41:28.912+0300] [CRITICAL] - Uncaught Exception:
Traceback (most recent call last):
  File "C:/Users/Aleee/!AlertApp/main.py", line 109, in <module>
    w = MainWindow()
  File "C:/Users/Aleee/!AlertApp/main.py", line 30, in __init__
    self.set_children_connections()
AttributeError: 'MainWindow' object has no attribute 'set_children_connections' (__init__.py:95)
[2022-09-29 22:27:00.482+0300] [CRITICAL] - Uncaught Exception:
Traceback (most recent call last):
  File "C:/Users/Aleee/!AlertApp/main.py", line 110, in <module>
    w = MainWindow()
  File "C:/Users/Aleee/!AlertApp/main.py", line 68, in __init__
    self.connect_chbs_to_tv(self.ui.tv)
  File "C:/Users/Aleee/!AlertApp/main.py", line 102, in connect_chbs_to_tv
    for chb in self.ui.sidewdg.findChildren(BuddyCheckBox):
NameError: name 'BuddyCheckBox' is not defined (__init__.py:95)
[2022-09-30 02:15:01.349+0300] [CRITICAL] - Uncaught Exception:
Traceback (most recent call last):
  File "C:/Users/Aleee/!AlertApp/main.py", line 111, in <module>
    w = MainWindow()
  File "C:/Users/Aleee/!AlertApp/main.py", line 32, in __init__
    self.initialize_cusstom_widgets()
  File "C:/Users/Aleee/!AlertApp/main.py", line 83, in initialize_cusstom_widgets
    widget.initialize()
  File "C:\Users\Aleee\!AlertApp\customobjects\QGroupBox.py", line 13, in initialize
    if str_to_int(self.settings.value(get_custom_property(button)[0])) == get_custom_property(button)[1]:
  File "C:\Users\Aleee\!AlertApp\methods.py", line 7, in str_to_int
    return int(text)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' (__init__.py:95)
[2022-09-30 02:16:00.714+0300] [CRITICAL] - Uncaught Exception:
Traceback (most recent call last):
  File "C:/Users/Aleee/!AlertApp/main.py", line 111, in <module>
    w = MainWindow()
  File "C:/Users/Aleee/!AlertApp/main.py", line 32, in __init__
    self.initialize_cusstom_widgets()
  File "C:/Users/Aleee/!AlertApp/main.py", line 83, in initialize_cusstom_widgets
    widget.initialize()
  File "C:\Users\Aleee\!AlertApp\customobjects\QGroupBox.py", line 13, in initialize
    if str_to_int(self.settings.value(get_custom_property(button)[0])) == get_custom_property(button)[1]:
  File "C:\Users\Aleee\!AlertApp\methods.py", line 7, in str_to_int
    return int(text)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' (__init__.py:95)
[2022-09-30 02:21:06.535+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:06.535+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:09.116+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:09.116+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:09.633+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:09.633+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:10.236+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:10.236+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:13.132+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:13.133+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:14.160+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:21:14.160+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:56:20.360+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:56:20.360+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:57:11.106+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:57:11.106+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:57:15.850+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:57:15.850+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:57:33.465+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
[2022-09-30 02:57:33.465+0300] [ERROR   ] - UPDATE query ("UPDATE patientinfo SET room = ?,oak_status = ?,oak_time = ?,oak_follow = ?,bak_status = ?,bak_time = ?,bak_follow = ?,trp_status = ?,trp_time = ?,trp_follow = ?,ddm_status = ?,ddm_time = ?,ddm_follow = ?,glu_status = ?,glu_time = ?,glu_follow = ?,oam_status = ?,oam_time = ?,oam_follow = ?,dia_status = ?,dia_time = ?,dia_follow = ?,acb_status = ?,acb_time = ?,acb_follow = ?,bnp_status = ?,bnp_time = ?,bnp_follow = ?,psp_status = ?,psp_time = ?,psp_follow = ?,agc_status = ?,agc_time = ?,agc_follow = ?,abc_status = ?,abc_time = ?,abc_follow = ?,xra_status = ?,xra_follow = ?,xra_time = ?,cts_status = ?,cts_time = ?,cts_follow = ?,usd_status = ?,usd_time = ?,usd_follow = ?,end_status = ?,end_time = ?,end_follow = ?,neur_status = ?,neur_time = ?,neur_follow = ?,card_status = ?,card_time = ?,card_follow = ?,rean_status = ?,rean_time = ?,rean_follow = ?,surg_status = ?,surg_time = ?,surg_follow = ?,urol_status = ?,urol_time = ?,urol_follow = ?,proc_status = ?,proc_time = ?,proc_follow = ? WHERE patient_id = ?") failed with error: database is locked Unable to fetch row (sqlwrapper.py:7)
